#!/usr/bin/env python3
# Copyright (c) 2017 James Beedy <jamesbeedy@gmail.com>

from argparse import ArgumentParser

from activities_lib import (
    activity_response_output_parser,
    get_activity_crud,
)


def create_parser():
    parser = ArgumentParser(
        description='activity-monitor',
        prog='activity-monitor'
    )

    parser.add_argument(
        'operation',
        help='Web request method to make',
        metavar='operation',
        type=str,
        choices=['create', 'list', 'get', 'update', 'delete']
    )
    parser.add_argument(
        '-a',
        '--activity-type',
        required=False,
        dest="activity_type",
        type=str,
        help='Data to add to request'
    )
    parser.add_argument(
        '-d',
        '--data',
        nargs="+",
        default=False,
        required=False,
        help='Activity type to update - only used with "update" operation'
    )

    parser.add_argument(
        '-v',
        '--version',
        action='version',
        version='%(prog)s 0.0.1'
    )

    parser.add_argument(
        "-f",
        '--format',
        help='format to json',
        dest='format',
        type=str,
        default='default'
    )
    return parser


def main():
    parser = create_parser()
    args = parser.parse_args()
    activity_crud = get_activity_crud(**args.__dict__)
    if args.format == 'default':
        activity_response_output_parser(args, activity_crud)
    elif args.format == 'json':
        print(json.dumps(activity_crud))


if __name__ == "__main__":
    main()
