#!/usr/bin/env python3
# Copyright (c) 2017 James Beedy <jamesbeedy@gmail.com>

from argparse import ArgumentParser
import sys

sys.path.append('.')


from activities_lib import (
    activity_response_output_parser,
    activity_type_get,
    activity_type_list,
    activity_type_update,
    activity_type_delete,
    activity_type_create,
)


def create_parser():
    parser = ArgumentParser(
        description='activity-monitor',
        prog='activity-monitor'
    )

    parser.add_argument(
        'operation',
        help='Web request method to make',
        metavar='operation',
        type=str,
        choices=['create', 'list', 'get', 'update', 'delete']
    )
    parser.add_argument(
        '-a',
        '--activity-type',
        required=False,
        dest="activity_type",
        type=str,
        help='Data to add to request'
    )
    parser.add_argument(
        '-d',
        '--data',
        nargs="+",
        default=False,
        required=False,
        dest="data",
        help='Activity type to update - only used with "update" operation'
    )

    parser.add_argument(
        '-v',
        '--version',
        action='version',
        version='%(prog)s 0.0.1'
    )

    parser.add_argument(
        "-f",
        '--format',
        help='format to json',
        dest='format',
        type=str,
        default='default'
    )
    return parser


def main():
    parser = create_parser()
    args = parser.parse_args()

    if args.operation == 'get':
        activity_crud = activity_type_get(args.activity_type)
    elif args.operation == 'list':
       activity_crud = activity_type_list()
    elif args.operation == 'delete':
       activity_crud = activity_type_delete(args.activity_type)
    elif args.operation == 'update':
       activity_crud = activity_type_update(args.activity_type, args.data)
    elif args.operation == 'create':
       activity_crud = activity_type_create(args.activity_type)

    #if args.format == 'default':
    #    activity_response_output_parser(args, activity_crud)
    #elif args.format == 'json':
    #    print(json.dumps(activity_crud))
    print(activity_crud)


if __name__ == "__main__":
    main()
